server:
  port: 8080

logging:
  level:
    root: INFO
    reactor:
      netty: INFO
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.springframework.cloud.gateway: INFO

application:
  frontend-url: http://localhost:3000

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://192.168.50.251:6180/auth/realms/humpback_dev
        registration:
          keycloak:
            client-id: humpback-gateway
            client-secret: a1246398-4c2f-46bd-b83d-9b1313f3378d
            # scope: openid,profile,offline_access,email,resource.read,roles
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      routes:
        - id: core
          uri: http://localhost:8260
          predicates:
            - Path=/**
          filters:
            - TokenRelay
            # - TokenRelayWithTokenRefresh
            - RemoveRequestHeader=Cookie, Set-Cookie

